load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "macOS",
    srcs = glob(["*.cc"]),
    hdrs = glob(["*.h"]),
    visibility = ["//visibility:public"],
    deps = [
        "@glog",
        "@com_github_gflags_gflags//:gflags",
        "//src/lib/core:core",
        "@glfw//:glfw",
    ],
)
