load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "platform",
    srcs = glob(["*.cc"]),
    hdrs = glob(["*.h"]),
    visibility = ["//visibility:public"],
    deps = [
        # "//src/lib/platform/windows:windows",
        # "//src/lib/platform/macOS:macOS",
    ],
)
